{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aiops.mysql.fullname" . }}
  labels:
    {{- include "aiops.mysqlLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    {{- include "aiops.mysqlLabels" . | nindent 4 }}
{{- end }}
